## kitty.conf
## https://sw.kovidgoyal.net/kitty/conf/


## Fonts
## https://sw.kovidgoyal.net/kitty/conf/#fonts

# VSAL=9  At symbol (`@`) with compact body
# cv07=3  `7` with straight stem, and serifs
# cv54=8  `t` with flat hook, crossbar at both sides of the vertical stem, and a shorter neck
# cv59=16 `y` with cursive shape, and a flat terminal hook; without serifs

# BEGIN_KITTY_FONTS
font_family      family="Iosevka Term" style="Regular" features="-calt VSAL=9 cv07=3 cv54=8 cv59=16"
bold_font        family="Iosevka Term" style="Bold"    features="-calt VSAL=9 cv07=3 cv54=8"
italic_font      family="Iosevka Term" style="Light"   features="-calt VSAL=9 cv07=3 cv59=16"
bold_italic_font family="Iosevka Term" style="Heavy"   features="-calt VSAL=9 cv07=3"
# END_KITTY_FONTS

font_size                       12.0


## Text cursor customization
## https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization

cursor_shape                    underline
cursor_beam_thickness           1.0
cursor_underline_thickness      1.0
cursor_stop_blinking_after      0.0


## Scrollback
## https://sw.kovidgoyal.net/kitty/conf/#scrollback

scrollback_lines                10000
scrollbar_width                 1.0
scrollbar_hover_width           1.5
scrollbar_radius                0.5
wheel_scroll_multiplier         1.0
wheel_scroll_min_lines          3
touch_scroll_multiplier         3.0


## Mouse
## https://sw.kovidgoyal.net/kitty/conf/#mouse

mouse_hide_wait                 0.0
url_style                       dotted
show_hyperlink_targets          yes
strip_trailing_spaces           smart
click_interval                  0.150

## Mouse actions

clear_all_mouse_actions         yes
include                         kitty.conf.d/mice.conf


## Performance tuning
## https://sw.kovidgoyal.net/kitty/conf/#performance-tuning

#input_delay                     1


## Terminal bell
## https://sw.kovidgoyal.net/kitty/conf/#terminal-bell

bell_path                       ~/.theme/bell


## Window layout
## https://sw.kovidgoyal.net/kitty/conf/#window-layout

remember_window_size            no
initial_window_width            140c
initial_window_height           40c
enabled_layouts                 splits,stack,horizontal,vertical,tall,fat,grid
window_resize_step_cells        1
window_resize_step_lines        1
window_border_width             1px
window_padding_width            2.0
single_window_padding_width     0.0
resize_in_steps                 yes
visual_window_select_characters jkl;uiopm,./
window_drag_tolerance           5.0


## Tab bar
## https://sw.kovidgoyal.net/kitty/conf/#tab-bar

tab_bar_style                   separator
tab_bar_align                   right
tab_separator                   "  "
active_tab_font_style           bold
inactive_tab_font_style         normal


## Color scheme
## https://sw.kovidgoyal.net/kitty/conf/#color-scheme

background_opacity              0.98
include                         current-theme.conf


## OS specific tweaks
## https://sw.kovidgoyal.net/kitty/conf/#os-specific-tweaks

macos_option_as_alt             yes
macos_show_window_title_in      window


## Keyboard shortcuts
## https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

clear_all_shortcuts             yes
include                         kitty.conf.d/keys.conf


## Advanced
## https://sw.kovidgoyal.net/kitty/conf/#advanced

close_on_child_death            yes
allow_remote_control            socket-only
listen_on                       unix:kitty
update_check_interval           0
shell_integration               no-cursor no-title
