require "user.variables"
require "user.autocommand"
require "user.keymap"
require "user.options"
require "user.usercommand"

require "user.fold"
require "user.ft"
require "user.kitty"
require "user.lsp"
