## Mappable actions
## https://sw.kovidgoyal.net/kitty/actions/


## Mouse actions
## https://sw.kovidgoyal.net/kitty/actions/#mouse-actions

# Click the link under the mouse or move the cursor
# https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Click-the-link-under-the-mouse-or-move-the-cursor
mouse_map left                  click ungrabbed                 mouse_handle_click selection link prompt
# Start selecting text
# https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Start-selecting-text
mouse_map left                  press ungrabbed                 mouse_selection normal

## Click the link under the mouse cursor
## https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Click-the-link-under-the-mouse-cursor
#mouse_map kitty_mod+left        release ungrabbed,grabbed       mouse_handle_click link
## Discard press event for link click
## https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Discard-press-event-for-link-click
#mouse_map kitty_mod+left        press grabbed                   discard_event
## Start selecting text
## https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Start-selecting-text
#mouse_map left                  press ungrabbed                 mouse_selection normal
## Select a word
##
## Paste from the primary selection
## https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Paste-from-the-primary-selection
#mouse_map middle                release ungrabbed               paste_from_selection
